# nath to your oh-my-zsh installation.
export ZSH=/Users/yfwang/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="muse"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

#source ~/.nvm/nvm.sh
#source ~/.nvm

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
 HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
## Example format: plugins=(rails git textmate ruby lighthouse)
## Add wisely, as too many plugins slow down shell startup.
#plugins=(git)

## User configuration

#export PATH=/usr/local/bin:/usr/local/sbin:${PATH}
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
## export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

## You may need to manually set your language environment
#export LANG=en_US.UTF-8

## Preferred editor for local and remote sessions
## if [[ -n $SSH_CONNECTION ]]; then
##   export EDITOR='vim'
## else
##   export EDITOR='mvim'
## fi

## Compilation flags
## export ARCHFLAGS="-arch x86_64"

## ssh
## export SSH_KEY_PATH="~/.ssh/dsa_id"

## Set personal aliases, overriding those provided by oh-my-zsh libs,
## plugins, and themes. Aliases can be placed here, though oh-my-zsh
## users are encouraged to define aliases within the ZSH_CUSTOM folder.
## For a full list of active aliases, run `alias`.
##
## Example aliases
## alias zshconfig="mate ~/.zshrc"
## alias ohmyzsh="mate ~/.oh-my-zsh"

#alias vim="/usr/local/bin/vim"
alias vi="/usr/local/bin/vim"

#export NVM_DIR="/Users/yfwang/.nvm"
#[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

## ruby
#export RBENV_ROOT=/usr/local/var/rbenv
#if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

#export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
#source /Users/yfwang/.rvm/scripts/rvm

# setting up the VirtualEnv
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Devel
source /usr/local/bin/virtualenvwrapper.sh

# change java8 to java7
export JAVA_HOME=$(/usr/libexec/java_home -v 1.7)
setjdk() {
  export JAVA_HOME=$(/usr/libexec/java_home -v $1)
}

export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/9.4/bin
#export DOCKER_HOST=tcp://192.168.59.103:2376
#export DOCKER_CERT_PATH=/Users/yfwang/.boot2docker/certs/boot2docker-vm
#export DOCKER_TLS_VERIFY=1

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

#export RBENV_ROOT="${HOME}/.rbenv"

#if [ -d "${RBENV_ROOT}" ]; then
  #export PATH="${RBENV_ROOT}/bin:${PATH}"
  #eval "$(rbenv init -)"
#fi
eval "$(thefuck --alias)"
# You can use whatever you want as an alias, like for Mondays:
eval "$(thefuck --alias FUCK)"

#eval "$(docker-machine env dev)"
. ~/.nvm/nvm.sh

#export JAVA_OPTS="-Dfile.encoding=UTF8 -Dspring.profiles.active=dev"
export JAVA_OPTS="-Dspring.profiles.active=dev -Dorg.apache.catalina.session.StandardSession.ACTIVITY_CHECK=true -Dfile.encoding=UTF8 -Djava.awt.headless=true -server -Xms512m -Xmx2048m -XX:NewSize=1m -XX:MaxNewSize=1536m -XX:PermSize=512m -XX:MaxPermSize=1024m -XX:+DisableExplicitGC"
#export JAVA_OPTS="-Dspring.profiles.active=dev -Dorg.apache.catalina.session.StandardSession.ACTIVITY_CHECK=true -Dfile.encoding=UTF8 -Djava.awt.headless=true -server -Xms512m -Xmx2048m -XX:NewSize=1m -XX:MaxNewSize=1536m -XX:PermSize=512m -XX:MaxPermSize=1024m -XX:+DisableExplicitGC"
export CATALINA_OPTS="-Dorg.apache.catalina.session.StandardSession.ACTIVITY_CHECK=true"

MYSQL=/usr/local/mysql/bin
export PATH=$PATH:$MYSQL
export DYLD_LIBRARY_PATH=/usr/local/mysql/lib:$DYLD_LIBRARY_PATH

[[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

export ANDROID_HOME=/usr/local/opt/android-sdk
export EDITOR='vim'
